baseURL = "https://www.infinitygroup.sk/"
title = "Infinity Group"
theme = "hugo-universal-theme"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

publishDir = "docs"

# Define the number of posts per page
paginate = 10

[markup.goldmark.renderer]
unsafe= true

[menu]

# Main menu

[[menu.main]]
    name = "Naša Spoločnosť"
    url  = "/our-company"
    weight = 1

[[menu.main]]
    name = "Novinky"
    url  = "/news/"
    weight = 2

[[menu.main]]
    name = "Produkty"
    identifier = "products"
    url  = "/products/"
    weight = 3

[[menu.main]]
    name = "Technológie"
    url  = "/machinery/"
    weight = 4

[[menu.main]]
    name = "Kontakt"
    url  = "/contact/"
    weight = 5

# Footer menu
[[menu.footer]]
    name = "Naša Spoločnosť"
    url  = "/our-company"
    weight = 1

[[menu.footer]]
    name = "Produkty"
    identifier = "products"
    url  = "/products/"
    weight = 2

[[menu.footer]]
    name = "Novinky"
    url  = "/news/"
    weight = 3

[[menu.footer]]
    name = "Technológie"
    url  = "/machinery/"
    weight = 4

[[menu.footer]]
    name = "Všeobecné obchodné podmienky"
    url  = "/terms-conditions/"
    weight = 5

[[menu.footer]]
    name = "Reklamačné podmienky"
    url  = "/return-conditions/"
    weight = 6

[[menu.footer]]
    name = "Ochrana osobných údajov"
    url  = "/gdpr/"
    weight = 7

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "MiroCillik"
    defaultKeywords = ["infinity", "laser", "kov", "kovo vyroba", "rezanie"]
    defaultDescription = "Infintiy Group website"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyAbxyc43gup7bG3wneA_sm7-LvcEQokrO4"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "marsala"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "mcillik@gmail.com"

    about_us = "<p></p>"
    copyright = "Copyright (c) 2018 - 2019, Infinity Group a.s.; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "2.1.2006"

    logo = "img/logo-infinity-7.png"
    address = """<p><strong>INFINITY GROUP a.s.</strong>
        <br>Pstruša 813
        <br>962 02 Vígľaš
        <br><strong>Slovensko</strong>
        <br>
        <br>email: <a href="mailto:infinity@infinitygroup.sk">infinity@infinitygroup.sk</a>
        <br>email (fakturácia): <a href="mailto:faktury@infinitygroup.sk">faktury@infinitygroup.sk</a>
        <br>tel: +421 455323806
      </p>
      """
    latitude = "48.5504092"
    longitude = "19.3051745"
    direction = "Infinity Gorup s.r.o, Pstruša 813, 962 02 Vígľaš, Slovakia"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file"
    title = "Využite naše služby!"
    subtitle = "Prijímame zákazky od niekoľko kusov až po milióny."
    link_url = "contact"
    link_text = "Kontaktovať"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Naši klienti"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Novinky"
    subtitle = ""
